### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'temperature'

### ISSUE THREAD

**Issue by wly1998** [rucmlcv/IEPT_FSL#4]
When I tried to eval the model, an AttributeError occured.

```
Traceback (most recent call last):

  File "eval.py", line 76, in <module>

    rot_loss, MI_loss, fsl_loss, final_loss, acc_list = model(data_shot, data_query)

  File "/cluster/home/wangluyang/.conda/envs/IEPT/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl

    result = self.forward(*input, **kwargs)

  File "/cluster/home/wangluyang/IEPT_FSL-master/SSL/models/ssl_proto.py", line 91, in forward

    support, query, proto, logitis = self.fsl_module_per_task(support_ang, query_ang)

  File "/cluster/home/wangluyang/IEPT_FSL-master/SSL/models/ssl_proto.py", line 66, in fsl_module_per_task

    logitis = logitis / self.args.temperature

AttributeError: 'Namespace' object has no attribute 'temperature'
```

Does anyone know how to deal with this error？

**Comment by BaochaoZhu** [comment]
Does anyone know how to deal with this error？
